# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimux < Formula
  desc "TUI dashboard for managing AI coding agent sessions"
  homepage "https://github.com/zanetworker/aimux"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zanetworker/aimux/releases/download/v0.9.0/aimux_0.9.0_darwin_amd64.tar.gz"
      sha256 "565437c9a567199aa228ee70966911ab0f5bc836c04dfb30cc39d5c05caf5cb5"

      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zanetworker/aimux/releases/download/v0.9.0/aimux_0.9.0_darwin_arm64.tar.gz"
      sha256 "a1a310e982e90c8d6ac9d3630e6678fc1636234a0692c04c6945b7e619b4b887"

      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zanetworker/aimux/releases/download/v0.9.0/aimux_0.9.0_linux_amd64.tar.gz"
      sha256 "42f3bd1d6ee84d8ba27f30a78401a8eac74319e340b5c370cff4d4fc6a211298"
      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zanetworker/aimux/releases/download/v0.9.0/aimux_0.9.0_linux_arm64.tar.gz"
      sha256 "03c1517d8a9bd98b762c51c795846c077253380bfecec72f14e86163bab11a31"
      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  test do
    assert_match "aimux", shell_output("#{bin}/aimux --version")
  end
end
