# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimux < Formula
  desc "TUI dashboard for managing AI coding agent sessions"
  homepage "https://github.com/zanetworker/aimux"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zanetworker/aimux/releases/download/v0.1.0/aimux_0.1.0_darwin_amd64.tar.gz"
      sha256 "5925071dac0390e01af87ec11d4328ffaf9a1def19b38c8ca537162289429847"

      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zanetworker/aimux/releases/download/v0.1.0/aimux_0.1.0_darwin_arm64.tar.gz"
      sha256 "873fa31d3ec694b076ec64870f7e0ba190924c286e098bb97ca11499645c3a5f"

      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zanetworker/aimux/releases/download/v0.1.0/aimux_0.1.0_linux_amd64.tar.gz"
      sha256 "dcab7e42a98d4b0c6b3cf8191480f8dadd881a8091af1ffffb913d03a42c1899"
      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zanetworker/aimux/releases/download/v0.1.0/aimux_0.1.0_linux_arm64.tar.gz"
      sha256 "9adedb0f30f6ac30431750d69f57639441ea926bb0774f0e07110d7919a81534"
      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  test do
    system "#{bin}/aimux", "--help"
  end
end
