# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimux < Formula
  desc "TUI dashboard for managing AI coding agent sessions"
  homepage "https://github.com/zanetworker/aimux"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zanetworker/aimux/releases/download/v0.2.0/aimux_0.2.0_darwin_amd64.tar.gz"
      sha256 "fe7940ee4edd8f018b3782ee8ae068a7e0760ecc64d03683cc54ef7c2086a8a1"

      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zanetworker/aimux/releases/download/v0.2.0/aimux_0.2.0_darwin_arm64.tar.gz"
      sha256 "5dfd36db629546e3139f2e83e066c6b79292e8e34540cce5e9d07d9e87f14aa1"

      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zanetworker/aimux/releases/download/v0.2.0/aimux_0.2.0_linux_amd64.tar.gz"
      sha256 "787ee03cd86862e4a4e3fa6055382e38895dfd5991b5b7f2ce781afd1a324278"
      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zanetworker/aimux/releases/download/v0.2.0/aimux_0.2.0_linux_arm64.tar.gz"
      sha256 "36b9d9bf09afe0eed004569faa719b415a84f661cf50dec81d112dbf08d34692"
      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  test do
    system "#{bin}/aimux", "--help"
  end
end
